[package]
name = "gnuradio-meta"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
description = "A module to efficiently read and write GNU Radio File Meta Sink files"

[dependencies]
thiserror = "2.0.16"
byteorder = "1"
fixed = "1.29.0"
num-complex = "0.4.6"
